FROM ubuntu:latest

RUN apt update \
    && apt upgrade -y \
    && apt -y install software-properties-common \
    && add-apt-repository ppa:deadsnakes/ppa \
    && apt -y install --no-install-recommends \
        build-essential \
        git \
        libssl-dev \
        python3-pip \
        python3.9 \
        python3.9-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /home/elastalert

COPY requirements*.txt ./

RUN pip3 install -U pip setuptools \
        && /usr/local/bin/pip3 install -r requirements-dev.txt
